//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreditCard.Inspector.Data.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CreditCardInspectorEntities : DbContext
    {
        public CreditCardInspectorEntities()
            : base("name=CreditCardInspectorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CARD_INFO> CARD_INFO { get; set; }
    
        public virtual ObjectResult<CARD_INFO> checkIfCreditCardExists(Nullable<long> cardNumber)
        {
            var cardNumberParameter = cardNumber.HasValue ?
                new ObjectParameter("CardNumber", cardNumber) :
                new ObjectParameter("CardNumber", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteStoreQuery<CARD_INFO>("exec checkIfCreditCardExists @CardNumber", cardNumberParameter);
        }
    }
}
