//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreditCard.Inspector.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARD_INFO
    {
        public System.Guid UID { get; set; }
        public string CARD_TYPE { get; set; }
        public long CARD_NUMBER { get; set; }
        public string VALID_THRU { get; set; }
    }
}
